# Generated by Django 3.2.16 on 2023-11-15 19:06

from django.db import migrations
from django.db import models
import django.db.models.deletion

import cats.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Цвет"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "цвет",
                "verbose_name_plural": "цвета",
                "default_related_name": "colors",
            },
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя кота"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Возраст кота")),
                ("weight", models.FloatField(verbose_name="Вес кота")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=cats.models.Cat.upload_to_folder,
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cats",
                        to="cats.color",
                    ),
                ),
            ],
            options={
                "verbose_name": "кот",
                "verbose_name_plural": "коты",
                "default_related_name": "cats",
            },
        ),
    ]
