# Generated by Django 3.2.16 on 2023-11-11 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cat",
            options={
                "default_related_name": "cats",
                "verbose_name": "кот",
                "verbose_name_plural": "коты",
            },
        ),
    ]
