# Generated by Django 3.2.16 on 2023-11-16 00:23

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=cats.models.Cat.upload_to_folder, verbose_name='Фото'),
        ),
    ]
