# Generated by Django 3.2.16 on 2023-11-11 21:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0002_alter_cat_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="age",
            field=models.IntegerField(verbose_name="Возраст кота"),
        ),
        migrations.AlterField(
            model_name="cat",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя кота"),
        ),
        migrations.AlterField(
            model_name="cat",
            name="weight",
            field=models.FloatField(verbose_name="Вес кота"),
        ),
    ]
