# Generated by Django 3.2.16 on 2023-11-16 20:32

from django.db import migrations
from django.db import models

import cats.validator


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0003_auto_20231116_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Кот отображается"
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[cats.validator.NameValidator()],
                verbose_name="Имя кота",
            ),
        ),
    ]
