# Generated by Django 3.2.16 on 2023-11-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20231112_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.fields.CharField>'),
        ),
    ]
