# Generated by Django 3.2.16 on 2023-11-19 23:20

from django.db import migrations
from django.db import models
import django.db.models.deletion

import cats.validator


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0004_auto_20231116_2332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="color",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colors",
                to="cats.color",
            ),
        ),
        migrations.AlterField(
            model_name="cat",
            name="slug",
            field=models.SlugField(
                max_length=255,
                unique=True,
                validators=[cats.validator.SlugValidator()],
                verbose_name="URL",
            ),
        ),
    ]
