# Generated by Django 3.2.16 on 2023-11-21 19:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                unique=True,
                verbose_name="Пользователь",
            ),
        ),
    ]
